// <auto-generated />
using MetasMermer.Repositories.EFCORE;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MetasMermer.Repositories.Migrations
{
    [DbContext(typeof(MetasMermerDbContext))]
    [Migration("20260204115957_aboutEntitysindekiImageLinkAlaniDeğiştirildi")]
    partial class aboutEntitysindekiImageLinkAlaniDeğiştirildi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Abouts.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("About");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "2007 Yılında Tokat'ın Niksar ilçesinde sanayi bölgesinde kurulan \"Metaş Mermer Ve Granit Sanayii kalitesini\" geliştirerek siz değerli müşterilerimize hizmet vermeye devam etmektedir..",
                            ImageLink = "[\"/img/hero.webp\",\"/img/kursat.webp\"]",
                            Title = "Her Zaman Kalite"
                        });
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Contacts.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Contact");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Value = "905325887656"
                        },
                        new
                        {
                            Id = 2,
                            Value = "905374480024"
                        },
                        new
                        {
                            Id = 3,
                            Value = "kursatersin@icloud.com"
                        },
                        new
                        {
                            Id = 4,
                            Value = "https://www.google.com/maps?ll=40.583868,36.919473&z=16&t=m&hl=tr&gl=TR&mapclient=embed&cid=13389469205681263836"
                        },
                        new
                        {
                            Id = 5,
                            Value = "Sanayi Sitesi 9.Blok No: 50 Niksar/Tokat"
                        },
                        new
                        {
                            Id = 6,
                            Value = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3030.0853262311134!2d36.91728441569593!3d40.58387195338053!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x407d1b6512db2dab%3A0xb9d0f34d57a9d4dc!2sMETA%C5%9E%20MERMER!5e0!3m2!1str!2str!4v1665173589058!5m2!1str!2str"
                        });
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Footers.Footer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FacebookLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InstagramLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Footer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FacebookLink = "https://www.facebook.com/metas.muratersin",
                            InstagramLink = "https://www.instagram.com/metasmuratersin"
                        });
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Galleries.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Gallery");
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Heroes.Hero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Hero");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Metaş Mermere"
                        });
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Solutions.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Solution");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = " Metaş mermer ve granit sanayii olarak her türlü • Mutfak Tezgahı • Denizlik • Basamak • Mezar işleriniz itina ile yapılır.",
                            Title = "Hizmetlerimiz"
                        });
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Users.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MetasMermer.Repositories.EFCORE.Whatsapps.Whatsapp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Whatsapp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Merhaba! 👋 Daha Fazla Bilgi İçin Bizlere Whatsapdan Ulaşabilirsiniz",
                            PhoneNumber = "905374480024",
                            Title = "Size Nasıl Yardımcı Olabilirim?"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
